name: Fluxo serviço
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check version Newman and Node
        run: |
          newman --version || echo "Newman is not installed"
          node --version || echo "Node.js is not installed"
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
      - name: Criar Servico
        run: |
          mkdir -p ./results
          newman run ./abrir-servico.json -e ./servico-env.json \
            --reporters cli,json \
            --reporter-json-export ./results/temp-criar-servico.json \
            --export-environment ./updated-env.json
      - name: Encaminhar Servico
        run: |
          newman run ./encaminhar-servico.json -e ./updated-env.json \
            --reporters cli,json \
            --reporter-json-export ./results/temp-encaminhar-servico.json \
            --export-environment ./updated-env.json
      - name: Finalizar Servico
        run: |
          newman run ./finalizar-insumo.json -e ./updated-env.json \
            --reporters cli,json \
            --reporter-json-export ./results/temp-finalizar-insumo.json \
            --export-environment ./updated-env.json
      - name: Combinar os arquivos JSON
        run: |
          jq -s 'reduce .[] as $item ({}; .run.executions += $item.run.executions)' \
            ./results/temp-criar-servico.json ./results/temp-encaminhar-servico.json ./results/temp-finalizar-insumo.json > ./results/final-report.json
      - name: Step 7 Exibir Erros no GitHub Actions
        run: |
          if jq -e '.run.failures | length > 0' ./results/final-report.json > /dev/null; then
            echo "❌ Erros encontrados nos testes!"
            exit 1
          else
            echo "✅ Todos os testes passaram com sucesso!"
          fi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report-html
          path: ./results/

      - name: Notificar Microsoft Teams
        if: always()
        run: |
            if [ "${{ job.status }}" == "success" ]; then
              STATUS="✅ Sucesso"
              COLOR="00FF00"
            else
              STATUS="❌ Falha"
              COLOR="FF0000"
            fi
            PAYLOAD=$(cat <<EOF
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "themeColor": "$COLOR",
              "summary": "Status do Workflow",
              "sections": [{
                "activityTitle": "Status do Workflow",
                "activitySubtitle": "${{ github.workflow }}",
                "facts": [{
                  "name": "Repositório",
                  "value": "${{ github.repository }}"
                }, {
                  "name": "Branch",
                  "value": "${{ github.ref }}"
                }, {
                  "name": "Status",
                  "value": "$STATUS"
                }, {
                  "name": "Detalhes",
                  "value": "[Ver Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                }],
                "markdown": true
              }]
            }
            EOF
            )
            curl -X POST -H "Content-Type: application/json" \
              -d "$PAYLOAD" \
              "${{ secrets.TEAMS_WEBHOOK_URL }}"