name: Fluxo serviço
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version || echo "Newman is not installed"
          node --version || echo "Node.js is not installed"
          
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
        
      - name: Step 3 Criar Servico
        run: |
          mkdir -p ./results
          newman run ./abrir-servico.json -e ./servico-env.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./results/Report-Criar-Servico.html \
            --export-environment ./updated-env.json
      

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./results/
