name: Fluxo serviço
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version || echo "Newman is not installed"
          node --version || echo "Node.js is not installed"
          
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
        
      - name: Step 3 Criar Servico
        run: |
          mkdir -p ./results
          newman run ./abrir-servico.json -e ./servico-env.json \
            --reporters cli,json \
            --reporter-json-export ./results/temp-criar-servico.json \
            --export-environment ./updated-env.json

      - name: Step 4 Encaminhar Servico
        run: |
          newman run ./encaminhar-servico.json -e ./updated-env.json \
            --reporters cli,json \
            --reporter-json-export ./results/temp-encaminhar-servico.json \
            --export-environment ./updated-env.json

            - name: Step 4 Finalizar Servico
            run: |
              newman run ./finalizar-insumo.json -e ./updated-env.json \
                --reporters cli,json \
                --reporter-json-export ./results/temp-finalizar-insumo.json \
                --export-environment ./updated-env.json

      - name: Step 5 Combinar os arquivos JSON
        run: |
          jq -s '.[0].run.executions += .[1].run.executions | .[0]' \
            ./results/temp-criar-servico.json ./results/temp-encaminhar-servico.json ./results/temp-finalizar-insumo.json > ./results/final-report.json

      - name: Step 6 Exibir Erros no GitHub Actions
        run: |
          ERRORS=$(jq -r '
            .run.executions[] | 
            .item as $item | 
            .assertions[]? | 
            select(.error) | 
            "🔴 Falha no teste: " + $item.name + 
            "\n🔗 Endpoint: " + $item.request.url.raw + 
            "\n❌ Erro: " + .error.message + "\n"
          ' ./results/final-report.json)

          if [ -n "$ERRORS" ]; then
            echo "❌ Erros encontrados nos testes:"
            echo "$ERRORS"
            exit 1
          else
            echo "✅ Todos os testes passaram com sucesso!"
          fi

      - name: Step 7 Gerar Relatório HTML
        run: |
          newman run ./abrir-servico.json -e ./servico-env.json \
            --reporters htmlextra \
            --reporter-htmlextra-export ./results/Report.html

      - name: Step 8 Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./results/
