name: Fluxo serviço
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check version Newman and Node
        run: |
          newman --version || echo "Newman is not installed"
          node --version || echo "Node.js is not installed"

      - name: Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra

      - name: Criar Servico
        run: |
          mkdir -p ./results
          newman run ./abrir-servico.json -e ./servico-env.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./results/criar-servico.html \
            --export-environment ./updated-env.json

      - name: Encaminhar Servico
        run: |
          newman run ./encaminhar-servico.json -e ./updated-env.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./results/encaminhar-servico.html \
            --export-environment ./updated-env.json

      - name: Finalizar Servico
        run: |
          newman run ./finalizar-insumo.json -e ./updated-env.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./results/finalizar-insumo.html \
            --export-environment ./updated-env.json

      - name: Combinar os arquivos HTML (opcional)
        run: |
          cat ./results/criar-servico.html ./results/encaminhar-servico.html ./results/finalizar-insumo.html > ./results/final-report.html

      - name: Exibir Erros no GitHub Actions
        run: |
          if grep "failure" ./results/final-report.html; then
            echo "❌ Erros encontrados nos testes"
          else
            echo "✅ Todos os testes passaram com sucesso"
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report-html
          path: ./results/

      - name: Notificar Microsoft Teams
        if: always()
        run: |
            if [ "${{ job.status }}" == "success" ]; then
              STATUS="✅ Sucesso"
              COLOR="00FF00"
            else
              STATUS="❌ Falha"
              COLOR="FF0000"
            fi
            PAYLOAD=$(cat <<EOF
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions"
              "themeColor": "$COLOR",
              "summary": "Status do Workflow",
              "sections": [{
                "activityTitle": "Status do Workflow",
                "activitySubtitle": "${{ github.workflow }}",
                "facts": [{
                  "name": "Repositório",
                  "value": "${{ github.repository }}"
                }, {
                  "name": "Branch",
                  "value": "${{ github.ref }}"
                }, {
                  "name": "Status",
                  "value": "$STATUS"
                }, {
                  "name": "Detalhes",
                  "value": "[Ver Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                }],
                "markdown": true
              }]
            }
            EOF
            )
            curl -X POST -H "Content-Type: application/json" \
              -d "$PAYLOAD" \
              "${{ secrets.TEAMS_WEBHOOK_URL }}"